# Generated by Django 4.1.4 on 2022-12-12 20:38
#ESTE ARCHIVO SE CREA CUANDO USAMOS EL COMANDO python manage.py makemigrations, y nos dice los cambios que hará a la database

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('parrafo', models.TextField()),
                ('fecha_posteada', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

#PARA VER EL SQL DE TODO ESTO, USAMOS EL COMANDO DE
#python manage.py sqlmigrate la carpeta que contiene las migraciones y el archivo de la migración, osea este mismo el 0001_initial.py
#Por lo tanto, se buscaría así, python manage.py sqlmigrate blog 0001