# Generated by Django 4.2 on 2023-04-15 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-titulo']},
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='blog.categoria'),
        ),
    ]
